version: "3.8"

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: your_database_name
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_password
    ports:
      - "3306:3306"
    networks:
      - my-network

  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    networks:
      - my-network

  # excel-import-api:
  #   build: .
  #   container_name: excel-import-api-container
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - my-network

networks:
  my-network:
    driver: bridge
